name: Image release
on:
  workflow_run:
    workflows: ['Build and test']
    types:
      - completed
jobs:
  Pull-image-release-sh:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}
      - name: List files in the repository
        run: |
          ls -lah ${{ github.workspace }}
      - name: List files in the curr folder
        run: |
          ls -lah .
      - run: echo "üçè This job's status is ${{ job.status }}."
